"use client";
import {useState,useEffect} from 'react';
import {ArrowRight, CalendarDays, Heart, ShieldCheck, Download, Printer, Flower2, Check, RotateCcw, Copy, Mail, MessageSquare, Share2, Smartphone, ExternalLink, Phone as PhoneIcon, BookOpen as BookOpenIcon} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {calculate,today,iso,milestones,calendar} from '@/lib/pregnancy.mjs';
import PatientHome from '@/components/patient-home';
import PatientHandoff from '@/components/patient-handoff';
import CarePlan,{WarningSigns} from '@/components/care-plan';
import EducationLibrary from '@/components/education-library';
import {normalizeHandouts,handouts} from '@/lib/handouts.mjs';
import {createPatientLink,readPatientLink,readHandouts,patientForm,composeLinks,shareMessage} from '@/lib/patient-link.mjs';
const methods=[['period','Last period'],['conception','Conception'],['ivf','IVF transfer'],['ultrasound','Ultrasound'],['due','Due date']];
const format=(d:number,short=false)=>new Intl.DateTimeFormat('en-US',{month:short?'short':'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(d*86400000));
export default function Page(){
const [form,setForm]=useState({method:'period',date:'',asOf:'',cycle:'28',embryo:'5',weeks:'12',days:'0'});
const [result,setResult]=useState<any>(null),[error,setError]=useState(''),[saved,setSaved]=useState(false),[notice,setNotice]=useState(''),[week,setWeek]=useState(20);
const [patient,setPatient]=useState(false),[visit,setVisit]=useState(false),[shareDue,setShareDue]=useState(''),[origin,setOrigin]=useState(''),[ready,setReady]=useState(false);
const [selectedHandouts,setSelectedHandouts]=useState<string[]>([]),[librarySession,setLibrarySession]=useState(0);
let patientLink='',linkError='';if(shareDue&&origin){try{patientLink=createPatientLink(origin,shareDue,selectedHandouts);}catch(e){linkError=(e as Error).message;}}
const compose=composeLinks(patientLink);
useEffect(()=>{
 const isVisit=new URLSearchParams(window.location.search).get('visit')==='1';setVisit(isVisit);setOrigin(window.location.origin+window.location.pathname);setForm(f=>({...f,method:isVisit?'due':'period',asOf:iso(today())}));
 function load(f:typeof form,patientView:boolean){const r=calculate(f);setForm(f);setResult(r);setWeek(Math.min(42,Math.max(1,r.weeks)));setPatient(patientView);}
 try{const due=readPatientLink(window.location.hash);if(due){setSelectedHandouts(readHandouts(window.location.hash));load(patientForm(due),true);setVisit(false);return;}if(isVisit)return;try{const raw=localStorage.getItem('bloom-pregnancy');if(raw){const stored=JSON.parse(raw);setSelectedHandouts(normalizeHandouts(stored._handouts||[]));const f={...stored,asOf:iso(today())};if(f.date)load(f,stored._view==='patient');else setForm(f);setSaved(true);}}catch{setNotice('Saved dates could not be loaded. Please enter your dates again.');}}
 catch(e){setError((e as Error).message);}finally{setReady(true);}
},[]);
useEffect(()=>{if(result)setShareDue(iso(result.due));},[result]);
useEffect(()=>{function changed(){try{const due=readPatientLink(window.location.hash);if(!due)return;setSelectedHandouts(readHandouts(window.location.hash));const next=patientForm(due),r=calculate(next);setForm(next);setResult(r);setWeek(Math.min(42,Math.max(1,r.weeks)));setPatient(true);setVisit(false);setSaved(false);setError('');setNotice('');}catch(e){setResult(null);setPatient(false);setError((e as Error).message);}}window.addEventListener('hashchange',changed);return ()=>window.removeEventListener('hashchange',changed);},[]);
useEffect(()=>{if(!patient||!form.date)return;function refresh(){const current=iso(today());if(current!==form.asOf){const next=patientForm(form.date,current);setForm(next);const r=calculate(next);setResult(r);setWeek(Math.min(42,Math.max(1,r.weeks)));}}const interval=window.setInterval(refresh,60000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return ()=>{window.clearInterval(interval);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};},[patient,form.date,form.asOf]);
function clearDates(){setSelectedHandouts([]);setLibrarySession(n=>n+1);try{localStorage.removeItem('bloom-pregnancy');}catch{}window.history.replaceState(null,'',window.location.pathname+(visit?'?visit=1':''));setSaved(false);setPatient(false);setResult(null);setShareDue('');setError('');setForm({method:visit?'due':'period',date:'',asOf:iso(today()),cycle:'28',embryo:'5',weeks:'12',days:'0'});setNotice(visit?'Ready for the next patient.':'Your dates and saved timeline have been cleared.');window.scrollTo({top:0,behavior:'smooth'});}
async function copyLink(){try{await navigator.clipboard.writeText(patientLink);setNotice('Patient link copied. Paste it into your chosen message.');}catch{setNotice('Copy is unavailable. Select and copy the patient link below.');}}
async function nativeShare(){try{if(navigator.share)await navigator.share({title:'Your pregnancy timeline',text:shareMessage(patientLink)});else await copyLink();}catch(e){if((e as Error).name!=='AbortError')setNotice('Sharing could not open. Use Copy link, Text, or Email.');}}
function followSection(e:React.MouseEvent){const link=(e.target as HTMLElement).closest('a');if(link?.getAttribute('href')?.startsWith('#')){const id=link.getAttribute('href')!.slice(1);e.preventDefault();if(!id)window.scrollTo({top:0,behavior:'smooth'});else document.getElementById(id)?.scrollIntoView({behavior:'smooth'});}}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'calculate_pregnancy_timeline',title:'Calculate pregnancy timeline',description:'Calculate and display a pregnancy timeline. Does not save dates or export a calendar.',inputSchema:{type:'object',properties:{method:{type:'string',enum:['period','conception','ivf','ultrasound','due']},date:{type:'string'},asOf:{type:'string'},cycle:{type:'string'},embryo:{type:'string'},weeks:{type:'string'},days:{type:'string'}},required:['method','date','asOf'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object')throw Error('Provide pregnancy date inputs.');const next={method:'period',date:'',asOf:'',cycle:'28',embryo:'5',weeks:'12',days:'0',...input};const r=calculate(next);setForm(next);setResult(r);setWeek(Math.min(42,Math.max(1,r.weeks)));setError('');return {dueDate:iso(r.due),weeks:r.weeks,days:r.days,daysUntilDue:r.remaining};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return ()=>lifecycle.abort();},[]);
function update(k:string,v:string){if(window.location.hash.includes('due='))window.history.replaceState(null,'',window.location.pathname+window.location.search);setPatient(false);setForm(f=>({...f,[k]:v}));setResult(null);setError('');setNotice('');}
function submit(e:React.FormEvent){e.preventDefault();try{const r=calculate(form);setResult(r);setWeek(Math.min(42,Math.max(1,r.weeks)));setError('');if(saved){try{localStorage.setItem('bloom-pregnancy',JSON.stringify({...form,_view:patient?'patient':'calculator',_handouts:selectedHandouts}));}catch{setNotice('Your result is ready, but this browser could not save the dates.');}}}catch(e){setError((e as Error).message);}}
function remember(value:boolean){setSaved(value);try{if(value)localStorage.setItem('bloom-pregnancy',JSON.stringify({...form,_view:patient?'patient':'calculator',_handouts:selectedHandouts}));else localStorage.removeItem('bloom-pregnancy');setNotice(value?'Your dates are saved only in this browser.':'Saved dates removed from this browser.');}catch{setSaved(false);setNotice('This browser does not allow saving dates.');}}
function download(){const url=URL.createObjectURL(new Blob([calendar(result)],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='bloom-pregnancy-timeline.ics';a.click();URL.revokeObjectURL(url);setNotice('Calendar downloaded. These are estimated milestones, not booked appointments.');}
if(patient&&result)return <PatientHome result={result} selected={selectedHandouts} download={download} clear={clearDates}/>;
return <div onClick={followSection} className={patient?'patient-view':''}><header><a className="brand" href="#"><Flower2 size={29}/> bloom<span>with Dr. Geffrey Klein</span></a><nav><a href={patient?"#journey":"#calculator"}>{patient?"My pregnancy":"Calculator"}</a><a href="#journey">Your timeline</a><a href="#patient-education">Patient guides</a></nav><a className="practice-link" href="https://geffreyklein.com" target="_blank" rel="noreferrer">Dr. Klein’s website <ExternalLink size={14}/></a></header>
<main><div className="view-switch"><a href="/">Pregnancy calculator</a><a href="/?visit=1" aria-current={visit?"page":undefined}>First OB visit</a></div>{!ready&&<p role="status">Loading your timeline…</p>}<div className="intro"><div className="eyebrow">{visit?"FOR YOUR FIRST OB VISIT":patient?"YOUR PERSONAL PREGNANCY TIMELINE":"A LITTLE CLARITY FOR YOUR NEXT CHAPTER"}</div><h1>{visit?"A timeline to take home.":<>Your pregnancy.<br className="mobile"/> One beautiful timeline.</>}</h1><p>{visit?"Enter the dating information, review the due date, and prepare a link for your patient.":patient?"Your weeks and days update automatically. Keep this link to come back anytime.":"Find your estimated due date and make sense of the weeks ahead."}</p></div>
<a className="urgent-shortcut" href="#warning-signs"><PhoneIcon size={16}/> Warning signs & when to call</a>
<div id="calculator" className={patient?"workspace patient-workspace":"workspace"}>{!patient&&<section className="calculator panel"><div className="section-heading"><span className="iconbox"><CalendarDays size={21}/></span><div><h2>{visit?"Pregnancy dating":"Let’s find your dates"}</h2><p>{visit?"Use your assigned due date or calculate from visit findings.":"Start with what you know."}</p></div></div><form onSubmit={submit}><div className="dating-field"><label id="dating-method-label" htmlFor="dating-method">Calculate using</label><Select value={form.method} onValueChange={v=>{if(v)update('method',String(v));}}><SelectTrigger id="dating-method" aria-labelledby="dating-method-label" className="dating-select"><SelectValue>{methods.find(([id])=>id===form.method)?.[1]}</SelectValue></SelectTrigger><SelectContent className="dating-options" alignItemWithTrigger={false} align="start">{methods.map(([id,label])=><SelectItem className="dating-option" key={id} value={id}>{label}</SelectItem>)}</SelectContent></Select></div><div className="dating-field"><label htmlFor="dating-date">{form.method==='period'?'First day of your last period':form.method==='conception'?'Conception / ovulation date':form.method==='ivf'?'Embryo transfer date':form.method==='ultrasound'?'Ultrasound date':'Assigned due date'}</label><input id="dating-date" type="date" required value={form.date} min="1900-01-01" max="2200-12-31" onChange={e=>update('date',e.target.value)}/></div>
{form.method==='period'&&<><label htmlFor="cycle">Average cycle length <span>days</span></label><input id="cycle" type="number" inputMode="numeric" min="21" max="45" required value={form.cycle} onChange={e=>update('cycle',e.target.value)}/><p className="helper">28 days is typical. Irregular cycles make period-based estimates less reliable.</p></>}
{form.method==='ivf'&&<fieldset className="embryo-field"><legend>Embryo age at transfer</legend><RadioGroup className="embryo-options" value={form.embryo} onValueChange={v=>update('embryo',String(v))} aria-label="Embryo age at transfer">{['3','5','6'].map(v=><label key={v} className={'embryo-choice '+(form.embryo===v?'chosen':'')} htmlFor={'embryo-'+v}><RadioGroupItem id={'embryo-'+v} value={v}/><span>Day {v}</span></label>)}</RadioGroup><p className="helper">Use the embryo age specified by your fertility clinic.</p></fieldset>}
{form.method==='ultrasound'&&<div className="split"><div><label htmlFor="weeks">Weeks at scan</label><input id="weeks" type="number" inputMode="numeric" min="0" max="42" required value={form.weeks} onChange={e=>update('weeks',e.target.value)}/></div><div><label htmlFor="days">Additional days</label><input id="days" type="number" inputMode="numeric" min="0" max="6" required value={form.days} onChange={e=>update('days',e.target.value)}/></div></div>}
<label htmlFor="asof">Calculate progress on</label><input id="asof" type="date" required min="1900-01-01" max="2200-12-31" value={form.asOf} onChange={e=>update('asOf',e.target.value)}/>{error&&<p role="alert" className="error">{error}</p>}<button className="primary" type="submit">{visit?"Calculate patient timeline":"Calculate my timeline"} <ArrowRight size={18}/></button>{!visit&&<div className="remember"><Checkbox id="remember" checked={saved} onCheckedChange={v=>remember(Boolean(v))}/><label htmlFor="remember">Remember my dates on this device</label></div>}{visit&&<p className="helper">Visit mode does not save dates on this computer.</p>}</form></section>}
<section className="result panel" aria-live="polite"><div className="eyebrow"><Heart size={15}/> {result?'YOUR ESTIMATED DUE DATE':'A NEW CHAPTER STARTS HERE'}</div>{result?<><h2 className="due">{format(result.due)}</h2><p className="result-sub">A date to look toward. A little room for the unexpected.</p><div className="stats"><div><strong>{result.elapsed<0?'Not started':`${result.weeks}w ${result.days}d`}</strong><span>on {format(result.start+result.elapsed,true)}</span></div><div><strong>{result.elapsed<0?'—':`Trimester ${result.trimester}`}</strong><span>{result.remaining>=0?`${result.remaining} days until due date`:`${-result.remaining} days past due date`}</span></div></div><div className="progress-label"><span>Your 40-week timeline</span><b>{Math.round(result.progress)}%</b></div><div className="progress" role="progressbar" aria-label="Progress toward estimated due date" aria-valuenow={Math.round(result.progress)} aria-valuemin={0} aria-valuemax={100}><i style={{width:result.progress+'%'}}/></div><div className="progress-ends"><span>Week 0</span><span>Week 40</span></div>{result.elapsed<0&&<p className="notice">This is a future timeline: pregnancy dating has not started on the selected date.</p>}{result.elapsed>=294&&<p className="notice">This date is at or beyond 42 weeks. If still pregnant, contact your maternity team about your care plan.</p>}<div className="result-actions"><button onClick={download}><Download size={16}/> Export calendar</button><button onClick={()=>window.print()}><Printer size={16}/> Print</button></div></>:<div className="empty"><div className="orbit"><Heart size={40} strokeWidth={1.3}/></div><h2>Every week is a step closer.</h2><p>Enter your dates to see your due date,<br/>current week, and personal timeline.</p><div className="empty-marks"><span>01 <small>Your dates</small></span><span>02 <small>Your journey</small></span><span>03 <small>What’s next</small></span></div></div>}<div className="result-note"><ShieldCheck size={18}/><p>Dates are calculated in your browser. A shared link contains the due date and any selected handouts; anyone with the link can view the timeline.</p></div></section></div>
<p className="status" role="status">{notice}</p>{patient&&<div className="patient-jumps"><a href="#patient-education"><BookOpenIcon size={17}/>My patient guides{selectedHandouts.length>0&&<b>{selectedHandouts.length}</b>}</a><a href="#journey"><CalendarDays size={17}/>My timeline</a><a href="#warning-signs"><PhoneIcon/>When to call</a></div>}
{result&&!patient&&<section className="share-panel panel" aria-labelledby="share-heading"><div className="section-heading"><span className="iconbox"><Share2 size={21}/></span><div><h2 id="share-heading">Send a timeline home</h2><p>Review the due date you want this patient to use.</p></div></div><div className="share-layout"><div><label htmlFor="share-due">Due date to share</label><input id="share-due" type="date" min="1900-01-01" max="2200-12-31" value={shareDue} onChange={e=>setShareDue(e.target.value)}/><p className="helper">This date controls the patient’s timeline. Editing it here does not change the calculation above.</p>{linkError&&<p className="error" role="alert">{linkError}</p>}</div><div><label htmlFor="patient-link">Patient link</label><input id="patient-link" type="text" readOnly value={patientLink} onFocus={e=>e.target.select()}/><p className="helper">Contains the due date and selected handout IDs. No name, birth date, or contact details.</p></div></div><div className="share-reading-summary"><div><BookOpenIcon/><span><b>{selectedHandouts.length?`${selectedHandouts.length} handouts included`:'Add a personal reading list'}</b><small>{selectedHandouts.length?selectedHandouts.map(id=>handouts.find(h=>h.id===id)?.title).join(' · '):'Choose guides from the library to highlight for this patient.'}</small></span></div><a href="#patient-education">{selectedHandouts.length?'Edit handouts':'Choose handouts'} <ArrowRight size={16}/></a></div><PatientHandoff link={patientLink} visit={visit}/><p className="helper">Text and Email open a draft in your messaging app for you to address and send. Anyone with the link can see the due date and selected topics. Use your practice’s approved communication process.</p>{visit&&<button className="next-patient" onClick={clearDates}><RotateCcw size={16}/> Start next patient</button>}</section>}
{patient&&result&&<section className="phone-panel panel" aria-labelledby="phone-heading"><div className="section-heading"><span className="iconbox"><Smartphone size={23}/></span><div><h2 id="phone-heading">Keep your timeline close</h2><p>Save this link on your phone to check your progress anytime.</p></div></div><div className="phone-actions"><button onClick={()=>remember(true)}><Check size={17}/>{saved?'Saved on this device':'Save on this device'}</button><button onClick={copyLink}><Copy size={17}/> Copy my link</button></div><p className="helper">Saving lets this browser remember your timeline. On a shared device, use your personal link instead.</p><details><summary>How to save it on my phone <span>+</span></summary><p><b>iPhone:</b> Open this link in Safari. Tap Share, then Add Bookmark or Add to Home Screen. Menu labels may vary. <a href="https://support.apple.com/guide/iphone/bookmark-a-website-iph42ab2f3a7/ios" target="_blank" rel="noreferrer">Apple instructions ↗</a></p><p><b>Android:</b> Open this link in Chrome. Open the menu (⋮), then bookmark the page or choose Add to Home screen → Create shortcut if available. <a href="https://support.google.com/chrome/answer/15085120?co=GENIE.Platform%3DAndroid" target="_blank" rel="noreferrer">Android instructions ↗</a></p><p>Keep the complete link, including everything after #. If your care team revises your due date, use the new link they provide. An older link will keep its original due date.</p></details><p className="helper">This timeline is for reference. Contact your care team with medical questions; this page does not send messages to the office.</p></section>}

<EducationLibrary key={librarySession} patient={patient} visit={visit} selected={selectedHandouts} onChange={setSelectedHandouts} hasResult={Boolean(result)}/>
<section id="journey" className="journey"><div className="heading-row"><div><div className="eyebrow">THE WEEKS AHEAD</div><h2>Your journey, at a glance.</h2></div><span className="pill">{result?'Personalized to your dates':'Explore a typical timeline'}</span></div><div className="trimester-grid">{[1,2,3].map((n)=><article key={n} className={'trimester t'+n}><span className="eyebrow">0{n} / TRIMESTER</span><h3>{['The beginning','Growing together','Getting ready'][n-1]}</h3><p>{['Weeks 0–13','Weeks 14–27','Week 28 onward'][n-1]}</p>{result&&<b>{format(result.start+[0,98,196][n-1],true)}</b>}</article>)}</div>
<div className="timeline panel"><div className="week-browser"><div><h3>Explore your weeks</h3><p>Select a week to see its dates and place in your timeline.</p></div><label className="week-input" htmlFor="browse">Week <input id="browse" type="number" min="1" max="42" value={week} onChange={e=>setWeek(Math.min(42,Math.max(1,Number(e.target.value))))}/></label></div><div className="week-grid">{Array.from({length:42},(_,i)=>i+1).map(w=><button key={w} aria-label={'Explore week '+w} aria-pressed={week===w} className={week===w?'selected':''} onClick={()=>setWeek(w)}>{w}</button>)}</div><div className="week-detail"><CalendarDays size={23}/><div><h3>{week} weeks pregnant · Trimester {week<14?1:week<28?2:3}</h3><p>{result?`${format(result.start+week*7,true)} – ${format(result.start+week*7+6,true)}`:'Calculate your timeline above to add your personal dates.'}</p></div><span>{week<40?`${40-week} weeks to due date`:week===40?'Your due-date week':'Beyond your due date'}</span></div><details className="milestone-details"><summary>Pregnancy milestones <span>+</span></summary><div className="milestones">{milestones.filter(m=>m.week>0).map(m=><div className="milestone" key={m.week}><div className={'dot '+(result&&result.elapsed>=m.week*7?'passed':'')}>{result&&result.elapsed>=m.week*7?<Check size={13}/>:null}</div><span className="week-label">WEEK {m.week}</span><div><h4>{m.title}</h4><p>{m.text}</p></div><time>{result?format(result.start+m.week*7,true):'—'}</time></div>)}</div></details></div><CarePlan result={result}/></section>
<WarningSigns/>
<section className="education" id="questions"><div><div className="eyebrow">A LITTLE REASSURANCE</div><h2>Good to know.</h2><p>Dates are a starting point.<br/>Your maternity team brings the full picture.</p></div><div>{[['How is my due date calculated?','Last period: 280 days plus the difference between your cycle length and 28 days. Known conception: 266 days. IVF: 266 days minus embryo age from transfer. Ultrasound: 280 days minus the gestational age measured at the scan. A known due date is used directly.'],['How accurate is a due date?','A due date is an estimate, not a guaranteed birthday. Early ultrasound can refine pregnancy dating. Keep the due date assigned by your clinician, especially for irregular cycles, uncertain dates, or assisted reproduction.'],['Why does pregnancy start before conception?','Gestational age conventionally starts around two weeks before conception. This gives clinicians a common way to measure pregnancy in weeks and days.'],['Does this work for twins or multiples?','These methods can estimate the 40-week due date for multiples, but they do not predict delivery timing. Your specialist will advise on an individualized monitoring and delivery plan.'],['What happens to my information?','Calculations happen in your browser. Saving on a device is optional. A patient link contains the due date and any selected handout IDs in the part after #; this part is not included in normal requests to our hosting server. The link is not encrypted or password-protected. Anyone with it can view the timeline, and messaging apps may retain it. Clear saved dates on shared devices. Calendar exports also contain personal dates.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
<footer><div><a className="brand" href="#"><Flower2/> bloom</a><p>Made for the weeks that matter.</p></div><div><p>Educational estimates only. Confirm dates and care decisions with your maternity team.</p><div className="sources"><a href="https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2017/05/methods-for-estimating-the-due-date" target="_blank" rel="noreferrer">ACOG dating guidance ↗</a><a href="https://www.nhs.uk/pregnancy/your-pregnancy-care/ultrasound-scans/" target="_blank" rel="noreferrer">NHS scan guidance ↗</a><button onClick={clearDates}><RotateCcw size={13}/> Clear my dates</button></div></div></footer></main></div>}
