'use client';
import {CalendarDays,Phone,TriangleAlert,ArrowUpRight,ShieldCheck,Syringe} from 'lucide-react';
import {careSchedule,careWindow,careStatus,vaccineWindow,rsvSeasonWindow,warningSigns} from '@/lib/care-plan.mjs';
const date=(day:number)=>new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(day*86400000));
const range=(w:{start:number;end:number|null})=>w.end===null?`${date(w.start)} onward`:`${date(w.start)} – ${date(w.end)}`;
export function WarningSigns(){return <section id="warning-signs" className="warning-panel" aria-labelledby="warning-title"><div className="warning-heading"><TriangleAlert size={25}/><div><span className="eyebrow">DON’T WAIT FOR YOUR NEXT VISIT</span><h2 id="warning-title">When to call right away</h2></div></div><p>Call our office immediately or go to Labor & Delivery for:</p><ul>{warningSigns.map(sign=><li key={sign}>{sign}</li>)}</ul><div className="warning-actions"><a href="tel:+12815570300"><Phone size={18}/> Call (281) 557-0300</a><a href="https://www.hcahoustonhealthcare.com/locations/clear-lake/specialties/womens-care/labor-and-delivery" target="_blank" rel="noreferrer">Clear Lake Labor & Delivery <ArrowUpRight size={17}/></a></div><p className="after-hours"><b>After hours:</b> Call our office or go directly to HCA Houston Healthcare Clear Lake Labor & Delivery (Clear Lake Regional Medical Center). For a life-threatening emergency, call 911.</p></section>;}
export default function CarePlan({result}:{result:any}){
const tdap=result?vaccineWindow(result.start,27,36):null,rsv=result?rsvSeasonWindow(result.start):null;
return <><section className="care-plan" aria-labelledby="care-plan-title"><div className="heading-row"><div><div className="eyebrow"><CalendarDays size={16}/> YOUR VISITS & TESTS</div><h2 id="care-plan-title">What to expect, and when.</h2></div></div><p className="care-intro">Your practice’s usual care schedule, {result?'matched to your due date':'ready to personalize with your due date'}. These are planning windows, not booked appointments. Your care team may adjust your schedule.</p><div className="care-stages">{careSchedule.map(item=>{const status=result?careStatus(item,result):null;return <article key={item.id} className={'care-stage '+(status==='In your window'?'current-stage':'')}><div className="care-stage-time"><span className="care-weeks">{item.label}</span>{result&&<time>{range(careWindow(item,result.start))}</time>}{status&&<span className="care-status">{status}</span>}</div><div className="care-stage-content"><h3>{item.title}</h3><ul>{item.items.map(text=><li key={text}>{text}</li>)}</ul></div></article>;})}</div></section>
<section id="pregnancy-vaccines" className="vaccine-section" aria-labelledby="vaccine-title"><div className="heading-row"><div><div className="eyebrow"><ShieldCheck size={16}/> PROTECTING YOU & YOUR BABY</div><h2 id="vaccine-title">Vaccines during pregnancy</h2></div></div><p className="care-intro">Recommended vaccines help protect you and your newborn from serious illness. Discuss your vaccination history and timing with Dr. Klein.</p><div className="vaccine-grid"><article><span className="vaccine-tag"><Syringe size={16}/> 27–36 WEEKS</span><h3>Tdap</h3><p>Recommended during every pregnancy, preferably early in this window.</p>{tdap&&<time>{range(tdap)}</time>}</article><article><span className="vaccine-tag"><Syringe size={16}/> ANY TRIMESTER</span><h3>Flu vaccine</h3><p>Get the flu shot each flu season. The live nasal-spray flu vaccine is not used during pregnancy.</p></article><article><span className="vaccine-tag"><Syringe size={16}/> DISCUSS AT YOUR VISIT</span><h3>COVID-19</h3><p>Recommended by your practice. Discuss current recommendations, your vaccine history, and timing with Dr. Klein.</p></article><article><span className="vaccine-tag"><Syringe size={16}/> 32–36 WEEKS · SEASONAL</span><h3>RSV · Abrysvo</h3><p>Helps protect your newborn. Usually given September–January in this area. If you received it in an earlier pregnancy, ask about infant protection instead of another maternal dose.</p>{result&&(rsv?<time>Seasonal window: {range(rsv)}</time>:<p className="season-note">Your 32–36-week window falls outside the usual vaccination season. Ask your care team about protecting your baby after birth.</p>)}</article></div><div className="avoid-vaccines"><h3>Live vaccines: check before you receive one</h3><p><b>Avoid during pregnancy:</b> MMR, varicella (chickenpox), and live nasal-spray flu vaccine.</p><p><b>Yellow fever:</b> Usually avoided, but unavoidable travel may require an individual risk–benefit assessment with your clinician.</p></div><div className="vaccine-sources"><a href="https://www.cdc.gov/vaccines-pregnancy/hcp/vaccination-guidelines/index.html" target="_blank" rel="noreferrer">CDC pregnancy vaccine guidance ↗</a><a href="https://www.cdc.gov/rsv/hcp/vaccine-clinical-guidance/pregnant-people.html" target="_blank" rel="noreferrer">RSV timing & eligibility ↗</a><span>Guidance checked September 7, 2026</span></div></section></>;
}
