'use client';
import {readingUrl,hasMobileGuide} from '@/lib/guide-links.mjs';
import {useState} from 'react';
import {BookOpen,ArrowUpRight,Search,Plus,Check,X,Files,HeartHandshake,ArrowUp,Phone} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {handouts,categories,welcome,filterHandouts} from '@/lib/handouts.mjs';
type Props={patient:boolean;visit:boolean;selected:string[];onChange:(ids:string[])=>void;hasResult:boolean};
export default function EducationLibrary({patient,visit,selected,onChange,hasResult}:Props){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('All'),[language,setLanguage]=useState('All'),[limit,setLimit]=useState(9);
 const docs=filterHandouts(query,category,language),chosen=selected.map(id=>handouts.find(h=>h.id===id)).filter(Boolean) as typeof handouts;
 const selecting=!patient&&(visit||hasResult);
 function toggle(id:string){onChange(selected.includes(id)?selected.filter(x=>x!==id):[...selected,id]);}
 function reset(){setQuery('');setCategory('All');setLanguage('All');setLimit(9);}
 const pdf=(doc:typeof handouts[number],label='Read guide')=><a className="pdf-link" href={readingUrl(doc)} target="_blank" rel="noreferrer" aria-label={`${label}: ${doc.title}`}>{hasMobileGuide(doc.id)?label:label==='Read guide'?'Open PDF':label}<ArrowUpRight size={17}/></a>;
 return <section id="patient-education" className="reading-room" aria-labelledby="reading-title">
 <div className="reading-heading"><div><div className="eyebrow"><BookOpen size={16}/> FROM DR. KLEIN’S LIBRARY</div><h2 id="reading-title">A little knowledge.<br/>A lot of reassurance.</h2><p>{selecting?'Build a reading list for this visit. Your selections travel with the patient’s link.':'Your questions deserve thoughtful answers. Find your care team’s handouts, all in one place.'}</p></div><div className="library-seal"><BookOpen size={27}/><b>{handouts.length}</b><span>patient guides</span></div></div>
 {chosen.length>0&&<div className="personal-reading"><div className="personal-heading"><div><div className="eyebrow"><HeartHandshake size={16}/> {selecting?'THIS VISIT’S READING LIST':'SELECTED FOR YOUR VISIT'}</div><h3>{selecting?`${chosen.length} ${chosen.length===1?'guide':'guides'} to take home`:'A good place to begin.'}</h3></div>{selecting&&<button className="clear-selection" onClick={()=>onChange([])}>Clear selections</button>}</div><p>{selecting?'These guides will appear first when your patient opens the link.':'The guides included with your link are gathered here. The full library is always available below.'}</p><div className="chosen-grid">{chosen.map((doc,i)=><article key={doc.id} className="chosen-item"><span className="reading-number">{String(i+1).padStart(2,'0')}</span><div><h4>{doc.title}</h4><span className="document-meta">{doc.pages} {doc.pages===1?'page':'pages'} · {doc.language}</span></div>{pdf(doc,'Read')}{selecting&&<button className="remove-guide" onClick={()=>toggle(doc.id)} aria-label={'Remove '+doc.title}><X size={17}/></button>}</article>)}</div>{selecting&&<a className="review-link" href={hasResult?'#share-heading':'#calculator'}>{hasResult?'Review & share patient link':'Enter the due date to create a link'}<ArrowUp size={17}/></a>}</div>}
 <div className="welcome-feature"><div className="welcome-spine"><BookOpen size={33}/><span>THE<br/>WELCOME<br/>GUIDE</span><small>DR. KLEIN’S PRACTICE</small></div><div className="welcome-copy"><span className="eyebrow">START HERE · {welcome!.pages} PAGES</span><h3>Your pregnancy,<br/>with a little more confidence.</h3><p>Your welcome packet brings visits, tests, and everyday questions together in one helpful guide.</p><div className="welcome-actions">{pdf(welcome!,'Open welcome guide')}{selecting&&<button className="welcome-add" aria-pressed={selected.includes(welcome!.id)} onClick={()=>toggle(welcome!.id)}>{selected.includes(welcome!.id)?<Check size={17}/>:<Plus size={17}/>} {selected.includes(welcome!.id)?'Added to visit':'Add to visit'}</button>}</div></div></div>
 <div className="library-toolbar"><div><h3>Find what’s on your mind</h3><p>Browse by topic or search for a question.</p></div><label className="library-search"><Search size={20}/><span className="sr-only">Search patient handouts</span><input type="search" placeholder="Try nausea, travel, breastfeeding…" value={query} onChange={e=>{setQuery(e.target.value);setLimit(9);}}/>{query&&<button aria-label="Clear search" onClick={()=>{setQuery('');setLimit(9);}}><X size={17}/></button>}</label></div>
 <div className="library-filters"><div><label id="topic-label">Topic</label><Select value={category} onValueChange={v=>{setCategory(String(v));setLimit(9);}}><SelectTrigger className="dating-select" aria-labelledby="topic-label"><SelectValue>{category==='All'?'All topics':category}</SelectValue></SelectTrigger><SelectContent className="dating-options" alignItemWithTrigger={false}>{['All',...categories].map(c=><SelectItem className="dating-option" key={c} value={c}>{c==='All'?'All topics':c}</SelectItem>)}</SelectContent></Select></div><div><label id="language-label">Language</label><Select value={language} onValueChange={v=>{setLanguage(String(v));setLimit(9);}}><SelectTrigger className="dating-select" aria-labelledby="language-label"><SelectValue>{language==='All'?'All languages':language}</SelectValue></SelectTrigger><SelectContent className="dating-options" alignItemWithTrigger={false}>{['All','English','Español'].map(c=><SelectItem className="dating-option" key={c} value={c}>{c==='All'?'All languages':c}</SelectItem>)}</SelectContent></Select></div><span className="found-count" role="status">{docs.length} {docs.length===1?'guide':'guides'}{selecting&&` · ${selected.length} selected`}</span></div>
 <div className="handout-grid">{docs.slice(0,limit).map(doc=><article key={doc.id} className={'handout-card '+(selected.includes(doc.id)?'is-chosen':'')}><div className="card-top"><span className="topic-tag">{doc.category}</span>{selected.includes(doc.id)&&<span className="selected-mark" aria-label="Selected for this visit"><Check size={15}/></span>}</div><h4>{doc.title}</h4><p>{doc.description}</p><span className="document-meta"><Files size={14}/> {doc.pages} {doc.pages===1?'page':'pages'} · {hasMobileGuide(doc.id)?'Mobile guide + PDF':'PDF'} · {doc.language}</span><div className="handout-actions">{pdf(doc)}{selecting&&<button className="add-guide" aria-label={(selected.includes(doc.id)?'Remove ':'Add ')+doc.title+(selected.includes(doc.id)?' from visit':' to visit')} aria-pressed={selected.includes(doc.id)} onClick={()=>toggle(doc.id)}>{selected.includes(doc.id)?<Check size={17}/>:<Plus size={17}/>} {selected.includes(doc.id)?'Added':'Add'}</button>}</div></article>)}</div>
 {docs.length===0&&<div className="library-empty"><Search size={28}/><h4>No guides match that search.</h4><p>Try a shorter search or choose another topic.</p><button onClick={reset}>Show all guides</button></div>}
 {docs.length>limit&&<button className="more-guides" onClick={()=>setLimit(n=>n+12)}>Show more guides <span>{docs.length-limit} more</span></button>}
 <div className="library-footnote"><BookOpen size={18}/><p>Handouts from Dr. Klein’s practice. Available mobile guides open as reading pages with the original PDF included. Other handouts open as PDFs in a new tab; use your phone’s Share menu to save a copy. A topic in this library does not mean you have that condition. Your care team can help you decide what applies to you.</p></div>
 <div className="care-contact"><div><b>Questions are part of the journey.</b><p>Your care team is here for the conversation.</p></div><a href="tel:+12815570300"><Phone size={17}/> (281) 557-0300</a><a href={handouts.find(d=>d.sourceFile==='When to call the doctor.pdf')!.url} target="_blank" rel="noreferrer">When to call <ArrowUpRight size={17}/></a></div>
 {selecting&&selected.length>0&&<div className="selection-dock"><span><Check size={17}/><b>{selected.length}</b> {selected.length===1?'guide':'guides'} selected</span><a href={hasResult?'#share-heading':'#calculator'}>{hasResult?'Review patient link':'Enter due date'}<ArrowUpRight size={17}/></a></div>}
 </section>;
}
