import {normalizeHandouts} from './handouts.mjs';
import {parseDate,iso,today,calculate} from './pregnancy.mjs';
export function validateDueDate(value){const day=parseDate(value);if(day<parseDate('1900-01-01')||day>parseDate('2200-12-31'))throw Error('Enter a due date between 1900 and 2200.');return value;}
export function createPatientLink(origin,dueDate,handouts=[]){validateDueDate(dueDate);const url=new URL(origin);if(!['https:','http:'].includes(url.protocol))throw Error('Use a website address.');url.search='';const ids=normalizeHandouts(handouts);url.hash=new URLSearchParams(ids.length?{v:'2',due:dueDate,docs:ids.join(',')}:{v:'1',due:dueDate}).toString();return url.href;}
export function readPatientLink(hash){const params=new URLSearchParams(hash.replace(/^#/,''));if(!params.has('due')&&!params.has('v'))return null;if(params.getAll('v').length!==1||!['1','2'].includes(params.get('v'))||params.getAll('due').length!==1)throw Error('This patient link is incomplete or unsupported. Ask your care team for a new link.');try{return validateDueDate(params.get('due'));}catch{throw Error('This patient link contains an invalid due date. Ask your care team for a new link.');}}
export function patientForm(dueDate,asOf=iso(today())){validateDueDate(dueDate);const form={method:'due',date:dueDate,asOf,cycle:'28',embryo:'5',weeks:'12',days:'0'};calculate(form);return form;}
export function shareMessage(link){return `Here is your pregnancy timeline from Dr. Geffrey Klein. Open this link to see your due date and current pregnancy week and any selected handouts, then bookmark it on your phone. If your care team changes your due date, please request an updated link.\n\n${link}`;}
export function composeLinks(link){const body=encodeURIComponent(shareMessage(link));return {email:`mailto:?subject=${encodeURIComponent('Your pregnancy timeline')}&body=${body}`,sms:`sms:?body=${body}`};}

export function readHandouts(hash){const p=new URLSearchParams(hash.replace(/^#/,''));if(p.get('v')!=='2')return [];const raw=p.get('docs')||'';if(raw.length>1000||p.getAll('docs').length>1)throw Error('This reading list is invalid. Ask your care team for a new link.');return normalizeHandouts(raw?raw.split(','):[]);}
